version: '3.9'

services:
  mongo:
    image: mongo:6.0
    restart: always
    container_name: yelpcamp-mongodb
    ports:
      - "27017:27017"
    volumes:
      - yelpcamp-db:/data/db
    networks:
      - app-network

  server:
    build: ./app/server
    image: hoangdesu/yelpcamp-mern-server:latest
    container_name: yelpcamp-server-container
    ports:
      - "3001:3001"
    volumes:
      - ./app/server:/app/server
      - /app/server/node_modules
    env_file: ./app/server/.env.docker
    environment:
      - NODE_ENV=dev
    depends_on:
      - mongo
    networks:
      - app-network
      
  client:
    build: ./app/client
    image: hoangdesu/yelpcamp-mern-client:latest
    container_name: yelpcamp-client-container
    ports:
      - "5173:5173"
    env_file:
      - ./app/client/.env
      - ./app/client/.env.docker
    networks:
      - app-network
    stdin_open: true
    volumes:
      - ./app/client:/app/client
      - /app/client/node_modules
      - ./imgs:/imgs

networks:
    app-network:
        driver: bridge

volumes:
  yelpcamp-db:
    driver: local
