# fly.toml app configuration file generated for yelp-camp-server on 2023-09-08T19:34:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yelp-camp-server"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
